- name: Pack 6 bot. 1.5L LA SERRETA
  price: '1.80'
  image: assets/img/productos/la-serreta-pack-6-botellas.png

- name: Pack 6 bot. 1.5L MONSSALUS
  price: '2.40'
  image: assets/img/productos/monssalus-pack-6-botellas.jpg

- name: Pack 24 bot. 0.33L ONLYWATER
  price: '6.50'
  image: assets/img/productos/onlywater-pack-24-botellas.png

- name: Pack 6 bot. 1.5L SOLÁN DE CABRAS
  price: '4.20'
  image: assets/img/productos/solancabras-pack-6-botellas.jpg

- name: Garrafa 5L MONSSALUS
  price: '1.25'
  image: assets/img/productos/monssalus-garrafa-5l.jpg

- name: Garrafa 8L LA SERRETA
  price: '1.45'
  image: assets/img/productos/la-serreta-garrafa-8l.jpg

- name: Pack 24 bot. 0.33L MONSSALUS
  price: '4.80'
  image: assets/img/productos/monssalus-pack-24-botellas.jpg

- name: Pack 12 bot. 0.33L LA SERRETA
  price: '1.80'
  image: assets/img/productos/la-serreta-pack-12-botellas.jpg
