- name: Pack 6 bot. 1.5L LA SERRETA
  price: 1.80
  image: assets/img/productos/la-serreta-pack-6-botellas.png

- name: Pack 6 bot. 1.5L MONSSALUS
  price: 2.40
  image: assets/img/productos/la-serreta-pack-6-botellas.png

- name: Pack 24 bot. 0.33L ONLYWATER
  price: 6.50
  image: assets/img/productos/la-serreta-pack-6-botellas.png
